- README.md
- rebar.config
- src/lasp_core.erl
- src/lasp_vnode.erl
Use the supplied ReadFun to ensure that we know how to properly route read requests when doing program rewriting for read_any, etc.
> Use supplied ReadFun.

- src/lasp_core.erl
- src/lasp_orset.erl
- src/lasp_orset_gbtree.erl
Dialyzes clean on 17.5 - no complaints about gb_trees escaping anymore
> Some dialyzer / code organization things

- include/lasp.hrl
- src/lasp_ivar.erl
- src/lasp_top_k_var.erl
Add prototype implementation of a top-k CRDT that assumes top-1 by default when called with the DT new() API.
> Add prototype top-k.

- include/lasp.hrl
- riak_test/lasp_leaderboard_test.erl
- src/lasp_lattice.erl
Add example showing how a top-k leaderboard, which is tolerant to message reordering and replay can be implemented in Lasp.  Include a simulation to show a correct execution.
> Add leaderboard example.

- riak_test/lasp_leaderboard_test.erl
- src/lasp_core.erl
- src/lasp_dt.erl
- src/lasp_lattice.erl
- src/lasp_top_k_var.erl
- src/lasp_type.erl
Add naive support for parametrized CRDTS, such as the top-K CRDT,
where a top-1 CRDT should differ from a top-2 CRDT.
Model types as tuples, that take the arguments used to initialize it:
for example, use the argument of a top-K CRDT to be the K value for that
given type.
> Add naive support for parametrized CRDTS.

- include/lasp.hrl
- src/lasp_core.erl
- src/lasp_plumtree_broadcast_distribution_backend.erl
- src/lasp_sup.erl
1. The delta_map has the limitation of the number of slots for storing deltas (`delta_mode_max_slots`).
2. When the slots are full, the first slot becomes an accumulator to store multiple deltas instead of deleting one of deltas (in order to avoid sending the entire state due to deleted deltas).
3. The delta_ack_map stores an extra boolean to check whether an 'ack' existed when the previous gc happened. With this boolean, we can check nodes are disconnected or slow and those nodes will be deleted during the next gc. This allows the deltas (garbage) to be collected after the disconnection of nodes.
4. The gc will happen after the certain number (`delta_mode_max_gc_counter`) of times of exchanges.
> Garbage collection for the delta-based anti-entropy strategy

- src/lasp_core.erl
- src/lasp_dependence_dag.erl
- src/lasp_plumtree_broadcast_distribution_backend.erl
- src/lasp_process.erl
- src/lasp_sup.erl
This pull request:
- Adds a prototype version of the dependency graph (5fb4b28afc52229aab73b0899c8b51fde0fe810d and b5454bf9654eca4a29933234e51aa15d6a2fe17d).
- Adds a "write" step to the lasp process (c8ccf43b5a63362e73e50b2d13472893aca8ecbe, 098a60389dc0e0ba18afcc80c703c771e2aead5e).
This is what we discussed the other day.
>Additional support for lasp processes in 3 steps: Read, Transform and
>Write.
>Now, instead of passing a single function that computes the changes and
>then writes them to the appropiate CRDT, we pass two functions, one that
>computes the new value, and another that writes the value.
- Tracks lasp processes as edges in the dag (1a4968944c12e0ff7cf26626cc5dc94c7ec4d0b4).
It won't create the process if it detects that it will form a loop, but won't
return an error. …
> Dependency graph

- src/lasp_dependence_dag.erl
- src/lasp_process.erl
Adds the read, write and transform functions as metadata to the dag.
Since we now have metadata, my next step is to detect lasp processes
that perform the same work (same edges, same transforming function)
so that we don't count them as two separate childs.
After that, the next optimization will detect all lasp processes connecting
(directly) two nodes and merge them into an union of all of them.
> Add function metadata to the dag

- src/lasp_core.erl
- src/lasp_dependence_dag.erl
- src/lasp_plumtree_broadcast_distribution_backend.erl
- src/lasp_process.erl
Track `read` and `bind` in the dag. `query` is tracked too since it doesn't use `read`.
~~Old lasp processes use non-tracked versions (`read_var` and `bind_var`), since I
couldn't get them to work with the tracked versions.~~
~~Todo: track `read_any`~~
> Track ephemerals (wip, don't merge)

- src/lasp_dependence_dag.erl
- src/lasp_process.erl
- src/lasp_sup.erl
- test/lasp_SUITE.erl
This PR implements path contraction and cleaving as a way to remove intermediate vertices in the graph.
- Detection of suitable paths to be contracted.
- Explicit optimization passes (calling `lasp_dependence_dag:contract()` will contract all suitable paths in the graph).
- Automatic cleaving based on vertex access behaviours. (Creating new edges involving removed vertices undoes any optimizations involving that vertex).
- Cycle detection on removed edges (`lasp_dependence_dag:will_form_cycle` will detect cycles even if the vertices were removed during a contraction in the graph).
- Autoupdating of vertex tags on process restart.
- Automatic contraction passes.
- Since cleavings happen _after_ an edge is created, reads and queries may be able to get old data from a removed vertex. This is …
> Dag path contraction

- src/lasp_default_broadcast_distribution_backend.erl
Plumtree can be easily overloaded; so periodically buffer updates and
broadcast them in an effort to reduce this problem.
> Buffer updates to plumtree.

- src/lasp_broadcast_buffer.erl
- src/lasp_default_broadcast_distribution_backend.erl
- src/lasp_sup.erl
broadcast() in the distribution backend needs to not use the gen_server,
because plumtree_broadcast:broadcast() calls back into the gen_server.
Therefore, store the buffer in a different gen_server that periodically
will call the broadcast module in the backend.
> Make buffer module.

- src/lasp_default_broadcast_distribution_backend.erl
- src/lasp_simulation_support.erl
- src/lasp_sup.erl
- test/lasp_client_server_advertisement_counter_SUITE.erl
Allow the convergence function to synchronize when there are partitions,
by using a user supplied filter function for filtering out the objects
to synchronize.
> Add object filter for convergence structure.

- src/lasp_sup.erl
The partisan_peer_service_manager is only ever read by partisan in partisan_config, not lasp_config.
> Correctly configure the peer service.

- src/lasp_config.erl
- src/lasp_core.erl
- src/lasp_default_broadcast_distribution_backend.erl
- src/lasp_sup.erl
- src/sprinter.erl
This parameter does not reflect the proper configuration of the
peer_service_manager in partisan, so remove it in favor of the other
configuration parameter.
> resolve incorrect include path.

- src/lasp_sup.erl
Don't always revert the peer service setting back to client/server
incase it's configured ahead of time by the test runner.
> Don't always revert setting.

- src/lasp_default_broadcast_distribution_backend.erl
Support the ability to use the partitioning percentage in the normal
state-based AAE exchanges.
> Support state-based partition injection.

- src/tutorial.erl
While the data structure is a set, the tutorial code is designed to
simplify the use and understanding of the interfaces, not to be
correct from an API standpoint. Those who would use the library would
not presumably rely on a tutorial wrapper.
A tuple in this case can be used to differentiate sets from sequences
> Return tuple from tutorial:query/2 instead of sets

- rebar.config
- rebar.lock
- src/lasp.app.src
The `pc` plugin does not appear to be used, so I've removed it from the config. I moved the `rebar3_auto` plugin to a new profile `auto` to be used as `rebar3 as auto auto` (I know that is kind of annoying, better to put personal dev tools like that in your global rebar3 config).
I also moved `erlcloud` to the relx config instead of .app.src. This allows me to override the lasp deps from my project to remove erlcloud without it complaining.
Do you do your experiments by running the release? If so this should be fine, if not then I'll have write something to remove it from the .app.src file of lasp on my end instead.
> move erlcloud to just be in the release and rm unused plugin

- src/lasp_default_broadcast_distribution_backend.erl
When a node creates a CRDT by declaring it, but without issuing an
actual mutation, it will create a bottom delta that *has* to be shipped
to the clients for them to bootstrap the object.
This is particularly problematic when the following happens:
1.) Server creates the CRDTs (at bottom.)
2.) Server sends them to client.
3.) Client performs the first mutation.
In this example, if the empty delta never gets sent to the clients, the
clients will never update the CRDT, therefore, they won't synchronize
the objects with the server, which will prevent the test from ever
converging.
> Fix failure to converge in reactive mode.

- rebar.config
I had tried `{nowarn_deprecated_function, [{gen_fsm, send_event, 2}]},` but this did not work for some reason, I'm going to ask around about that and possibly have to file a bug with OTP if I really am doing it right.
> do not warn/error on deprecated gen_fsm:send_event/2

- src/lasp_core.erl
Given that a register has a bottom value of undefined and not empty list, you need to convert this to ensure when it's undefined that it is actually a list.
> Ensure membership is always a list.

- src/lasp_core.erl
Avoid a situtation where single fire processes terminate after receiving the response and stay registered to receive updates on thresholds firing.  Avoids a situtation where the process stays registered and allows the ETS table to grow indefinitely, ultimately crashing the node.
> Prevent process leakage.

- simulations/lasp_simulation_support.erl
- src/lasp_core.erl
refactors instances where infix `++` can replace longer `lists.append(...)` cases
> refactor: simpler infix append
