lasp-lang/lasp

include/lasp.hrl
riak_test/lasp_adcounter_orset_test.erl
riak_test/lasp_advertisement_counter_test.erl
riak_test/lasp_bind_test.erl
riak_test/lasp_filter_test.erl
riak_test/lasp_fold_test.erl
riak_test/lasp_intersection_test.erl
riak_test/lasp_kvs_replica_test.erl
riak_test/lasp_map_test.erl
riak_test/lasp_monotonic_read_test.erl
riak_test/lasp_product_test.erl
riak_test/lasp_programs_test.erl
riak_test/lasp_union_test.erl
src/gb_trees_ext.erl
src/lasp_core.erl
src/lasp_example_keylist_program.erl
src/lasp_example_program.erl
src/lasp_execute_coverage_fsm.erl
src/lasp_execute_fsm.erl
src/lasp_gset.erl
src/lasp_lattice.erl
src/lasp_orset_gbtree.erl
src/lasp_program.erl
src/lasp_riak_index_program.erl
src/lasp_vnode.erl
test/crdt_statem_eqc.erl
test/lasp_eqc.erl

Add a observed-remove set variant built as a general balanced tree to allow coordinators of merges of the set to perform a streaming merge operation.

Add general balanced trees.

---

include/lasp.hrl
src/lasp_core.erl
src/lasp_process.erl
src/lasp_process_sup.erl
src/lasp_sup.erl
src/lasp_vnode.erl

Properly supervise all Lasp processes through a new abstraction called
the Lasp "process."  A Lasp "process" is a process that never
terminates; it reads input values from one or more CRDTs, transforms
them, and creates output values, both streams, of which are fully
monotonic.  This is the core abstraction in Lasp, and represents a
single node in the dataflow execution graph.

Lasp "process" abstraction.

---

.gitignore
README.md

Bring in some minor fixes for formatting and ignore files.

Minor fixes.

---

rebar.config
rel/files/app.config
src/lasp_hanoidb_storage_backend.erl

Add HanoiDB backend; use this backend as the default backend for the
Lasp runtime system.

Add HanoiDB backend.

---

riak_test/lasp_leaderboard_test.erl
src/lasp.erl
src/lasp_core.erl
src/lasp_distribution_backend.erl
src/lasp_plumtree_broadcast_distribution_backend.erl
src/lasp_type.erl

Add a query function that returns the most recent value of a particular CRDT.

Add query function.

---

riak_test/lasp_advertisement_counter_test.erl
riak_test/lasp_bind_test.erl
riak_test/lasp_filter_test.erl
riak_test/lasp_fold_test.erl
riak_test/lasp_intersection_test.erl
riak_test/lasp_kvs_replica_test.erl
riak_test/lasp_leaderboard_test.erl
riak_test/lasp_map_test.erl
riak_test/lasp_monotonic_read_test.erl
riak_test/lasp_product_test.erl
riak_test/lasp_union_test.erl
src/lasp.erl
src/lasp_core.erl
src/lasp_distribution_backend.erl
src/lasp_plumtree_broadcast_distribution_backend.erl

Have the declare operation return bottom value and metadata, which is needed to properly disseminate the information via the distribution protocol.

Declare returns bottom and metadata.

---

riak_test/lasp_dynamic_scope_test.erl
src/lasp.erl
src/lasp_core.erl
src/lasp_distribution_backend.erl
src/lasp_plumtree_broadcast_distribution_backend.erl

Fix various problems in the distribution layer where clocks are not incremented correctly, broadcasts are not performing proper merges of clock information, and finally introduce dynamic variables correctly.

Various improvements.

---

apps/lasp/priv/plots/advertisement_counter_read_latency.gnuplot
apps/lasp/src/lasp_advertisement_counter.erl
apps/lasp/src/lasp_plumtree_broadcast_distribution_backend.erl
apps/lasp/src/lasp_read_latency_instrumentation.erl
apps/lasp/src/lasp_simulate_resource.erl
apps/lasp/src/lasp_sup.erl

Add latency instrumentation for read operations.

Add latency instrumentation for reads.

---

apps/lasp/src/lasp_advertisement_counter.erl
apps/lasp/src/lasp_advertisement_counter_client.erl
apps/lasp/src/lasp_ets_storage_backend.erl
apps/lasp/src/lasp_read_latency_instrumentation.erl
apps/lasp/src/lasp_support.erl
apps/lasp/src/lasp_write_latency_instrumentation.erl

Work-in-progress profiling branch.

Profiling.

---

src/lasp_dets_storage_backend.erl
src/lasp_ets_storage_backend.erl
src/lasp_ivar.erl

Also, fix a few typos I happened to notice.

Pull out case statements to a function

---

.gitignore
src/lasp_ivar.erl
src/lasp_orset.erl
src/lasp_pair.erl

very minor, but a little spec/doc cleanup.

minor rewordings and type-specs

---

include/lasp.hrl
src/lasp_core.erl
src/lasp_plumtree_broadcast_distribution_backend.erl
src/lasp_process.erl
src/lasp_sup.erl
test/lasp_delta_SUITE.erl

A new test SUITE for incremental computation testing was also added.

Initial implementation of the incremental computation for map()

---

src/lasp_pncounter.erl

The minimal delta for an increment is the value of the increment component plus one and the decrement component as zero (and vice versa for the decrement).
Example:
```erlang
PNCnt  =  [{1, 10, 5}, {2, 7, 3}],
[{1, 11, 0}] = increment_by_one(1, PNCnt),
[{2, 0, 4}] = decrement_by_one(2, PNCnt).
```

Minimal Delta on PNCounter

---

bin/dcos-deploy.sh
include/lasp.hrl
rebar.lock
src/lasp_advertisement_counter.erl
src/lasp_advertisement_counter_client.erl
src/lasp_advertisement_counter_server.erl
src/lasp_core.erl
src/lasp_sup.erl

WIP; DO NOT MERGE.
This exists just for a temporary EC2 evaluation, for now.

Prototype advertisement counter evaluation.

---

priv/js/main.js
src/lasp_dag_resource.erl
src/lasp_dependence_dag.erl

Also, clean up the javascript a bit.

Return error code from to_dot when dependency graph is empty

---

src/lasp_sup.erl

Fix badmatch on lasp_sup when dag_enabled set to true

---

src/lasp_core.erl
src/lasp_dependence_dag.erl
src/lasp_process.erl

Stream operations weren't being tracked correctly in the dag.

Fix stream tracking

---

src/lasp_plumtree_broadcast_distribution_backend.erl
src/lasp_support.erl
test/lasp_advertisement_counter_SUITE.erl

Integration target for single node advertisement counter.

---

Makefile
include/lasp.hrl
rebar.lock
src/lasp_advertisement_counter_client.erl
src/lasp_advertisement_counter_server.erl
src/lasp_core.erl
src/lasp_plumtree_broadcast_distribution_backend.erl
src/lasp_support.erl
src/lasp_type.erl
test/lasp_advertisement_counter_SUITE.erl

WIP
- I don't see convergence being reached on state based (both) tests
- with deltas, it's not working because types repo has a bug (__update__: this is fixed now)

Convergence Tracking

---

.gitignore
.travis.yml
rebar.config
rebar.lock

Fix travis configuration.

---

Makefile
src/lasp_advertisement_counter_server.erl
test/lasp_advertisement_counter_overcounting_SUITE.erl
test/lasp_advertisement_counter_partition_overcounting_SUITE.erl

Overcounting

---

src/lasp_dependence_dag.erl
src/lasp_process.erl
src/lasp_sql_materialized_view.erl
src/lasp_sup.erl
test/lasp_SUITE.erl

Sql latency tests

---

src/lasp.erl
src/lasp_advertisement_counter_server.erl
src/sprinter.erl

Begin fleshing out what the invariant interface will look like.

Add invariants.

---

src/lasp_default_broadcast_distribution_backend.erl

Add a reactive client/server topology where messages are sent back with
the latest update when arrived.

Add reactive client/server.

---

include/lasp.hrl
rebar.lock
src/lasp_advertisement_counter_client.erl
src/lasp_advertisement_counter_server.erl
src/lasp_default_broadcast_distribution_backend.erl
src/lasp_game_tournament_client.erl
src/lasp_game_tournament_server.erl
src/lasp_marathon_simulations.erl
src/lasp_simulation_support.erl
src/lasp_sup.erl
test/lasp_client_server_game_tournament_SUITE.erl
test/lasp_peer_to_peer_game_tournament_SUITE.erl

Game Tournament Scenario

---

src/lasp_default_broadcast_distribution_backend.erl
src/lasp_type.erl

No combinator support, but base support for read/writes.

Initial support for awset.

---

src/lasp_plumtree_backend.erl

Make sure the node prefixes the timestamp with it's own identifier: this
means that we can have this tree participate in multiple trees, each
rooted at a different node.

Parameterize timestamps.

---

Dockerfiles/lasp-dev
Dockerfiles/lasp-exp

Use new image.

---

Makefile

A test that doesn't pass has been commented

Updating Makefile

---

rebar.lock

in order to clean up 'EXIT' messages.

update gen_flow to 0.0.4

---

.gitignore
src/lasp_distribution_backend.erl
src/lasp_state_based_synchronization_backend.erl
src/lasp_sup.erl
src/lasp_support.erl

When an update occurs, if this option is enabled, a metadata exchange will be triggered immediately.

Provide option to force propagation on update.

---

src/lasp.erl
src/lasp_distribution_backend.erl
src/lasp_state_based_synchronization_backend.erl

Support a function to initiate propagation for values by identifier.

Add propagate/1.

---

rebar.config
src/lasp.app.src

@tsloughter is there a way to make this application conditionally start for some nodes so I don't need to remove it -- having trouble with it working in some environments.

Remove os_mon.

---

samples/map.erl

Noticed the sample code didn't work on my shell (osx, OTP 20).  Now it matches the `readme.io` more.

Fixing sample code

---

README.md

This might be a stretch, but this blog post that has some code examples that seem quite clear.  Hopefully I can contribute something bigger once I start getting deeper.

Adding code examples to readme

---

.travis.yml

test erlang/otp 21

---

README.md

This explains how to launch two nodes in lasp, join them to a cluster and share data between them.

Add information on how to create a cluster
